### ISSUE TITLE
You can get super simple CI integration with Travis-CI

### ISSUE THREAD

**Issue by MartinNowak** [daehlith/statsd4d#4]
Basically you need a single `.travis.yml` file, to automatically run `dub test`.

``` yml
language: d
sudo: false
```

http://docs.travis-ci.com/user/languages/d/

**Comment by daehlith** [comment]
This is a great suggestion, I love using travis in other (non-D) projects so there's absolutely no reason to not use it here.

**Comment by daehlith** [comment]
This was indeed super easy to add, great job right there! (-: The only issue I noticed is that I couldn't specify different D compilers (as in ea949b501abeb16388e6cfe61deec7272d51235d ) - presumably this is because I was omitting the compiler version?

**Comment by MartinNowak** [comment]
Yes there are no default versions for the compilers yet. Not sure if it's really necessary to test this library on 6 different platforms as UDPSocket should be fairly stable and portable. Try to make fair use of the freely provided computing resources.

**Comment by daehlith** [comment]
Agreed on the fair use! It was purely a test to see if it's possible. (-:
